version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - "2379:2379"
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd=http://etcd:2380

  zetcd:
    image: quay.io/coreos/zetcd:v0.0.5
    ports:
      - "2181:2181"
    command: -endpoints etcd:2379 -zkaddr=:2181
    depends_on:
      - etcd

  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zetcd
    ports:
      - "19091:9092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 19091
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "logging:3:2"
    dns: 8.8.4.4
     #Ok, looks like the broker ids may persist for a while, so make sure we remove them before starting
    command: bash -c '/opt/kafka/bin/zookeeper-shell.sh zetcd:2181 rmr /brokers/ids/101 && start-kafka.sh'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka
    depends_on:
      - zetcd
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "logging:3:2"
    dns: 8.8.4.4
     #Ok, looks like the broker ids may persist for a while, so make sure we remove them before starting
    command: bash -c '/opt/kafka/bin/zookeeper-shell.sh zetcd:2181 rmr /brokers/ids/102 && start-kafka.sh'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    image: wurstmeister/kafka
    depends_on:
      - zetcd
    ports:
      - "19093:9092"
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 19093
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "logging:3:2"
    dns: 8.8.4.4
     #Ok, looks like the broker ids may persist for a while, so make sure we remove them before starting
    command: bash -c '/opt/kafka/bin/zookeeper-shell.sh zetcd:2181 rmr /brokers/ids/103 && start-kafka.sh'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
